import { LegalLayout } from "./legal";
import { Link } from "./router";
import { isSet, LEGAL_ENTITY, LEGAL_NAME, SUBPROCESSORS } from "./site-config";

/**
 * Data Processing Addendum. Workplace operators (the managers who create a
 * workplace) are the controller of the worker data in their workplace; jooling
 * processes that data on their documented instructions. This page incorporates
 * by reference into the Terms, so accepting the Terms accepts the DPA.
 */
export function DpaPage() {
	return (
		<LegalLayout
			eyebrow="Data Processing Addendum"
			title="How we process workplace data."
			intro={
				<>
					<p>
						This Data Processing Addendum ("DPA") applies where {LEGAL_NAME}
						{isSet(LEGAL_ENTITY.legalName) ? ` ("jooling")` : ""} processes
						personal data on behalf of a business customer that uses jooling for
						a workplace ("Customer", "you"). The Customer is the controller and
						jooling is the processor for the workplace data described below.
						This DPA is part of our Terms &amp; Conditions and applies
						automatically — there is nothing to sign. If your organization
						requires a countersigned copy, contact{" "}
						<a href={`mailto:${LEGAL_ENTITY.contactEmail}`}>
							{LEGAL_ENTITY.contactEmail}
						</a>
						.
					</p>
					<p>
						Capitalized terms not defined here have the meaning given in the
						Terms. This DPA is written to meet the requirements of Article 28 of
						the GDPR and equivalent UK and Swiss law.
					</p>
				</>
			}
			sections={[
				{
					id: "roles",
					heading: "1. Roles and scope",
					body: (
						<ul>
							<li>
								<strong>Controller:</strong> the Customer, for the personal data
								in its workplace.
							</li>
							<li>
								<strong>Processor:</strong> jooling, which processes that data
								only on the Customer's documented instructions (including
								through use of the Service's features) unless required to do
								otherwise by law, in which case jooling will inform the Customer
								before processing unless prohibited.
							</li>
							<li>
								<strong>Data subjects:</strong> the Customer's workers,
								managers, and other invited members, and any person appearing in
								workplace content.
							</li>
						</ul>
					),
				},
				{
					id: "details",
					heading: "2. Processing details",
					body: (
						<ul>
							<li>
								<strong>Subject matter:</strong> scheduling, availability,
								time-off, time tracking, attendance, and team communication for
								hourly teams.
							</li>
							<li>
								<strong>Duration:</strong> the term of the Customer's
								subscription, plus any post-termination period needed to provide
								an export before deletion.
							</li>
							<li>
								<strong>Nature and purpose:</strong> hosting, storage,
								retrieval, notification delivery, and support for workplace data
								entered into or generated by the Service.
							</li>
							<li>
								<strong>Categories of data:</strong> identity and contact data
								(name, email, phone), employment data (role, position,
								location), scheduling data (shifts, availability, swaps,
								time-off), time and attendance data, precise geolocation only
								where the Customer enables geofenced time entries, and messages
								exchanged within the workplace.
							</li>
						</ul>
					),
				},
				{
					id: "obligations",
					heading: "3. Processor obligations",
					body: (
						<ul>
							<li>
								Process workplace data only for the purposes in this DPA and
								keep it confidential.
							</li>
							<li>
								Ensure personnel authorized to process workplace data are bound
								by confidentiality obligations.
							</li>
							<li>
								Assist the Customer in responding to data subject requests
								(access, correction, deletion, restriction, objection,
								portability); the Service's export features let the Customer
								respond directly where possible.
							</li>
							<li>
								Notify the Customer without undue delay, and within 48 hours of
								becoming aware, of a personal data breach affecting workplace
								data, and provide information reasonably necessary for the
								Customer's own notification duties.
							</li>
							<li>
								Provide the information reasonably required to demonstrate
								compliance with this DPA and allow for audits described in
								section 6.
							</li>
							<li>
								Delete or return workplace data within 90 days after the
								Customer's subscription ends, except data jooling must keep by
								law.
							</li>
						</ul>
					),
				},
				{
					id: "security",
					heading: "4. Security",
					body: (
						<p>
							jooling maintains technical and organizational measures
							appropriate to the risk, including encryption of personal data in
							transit, access controls limited to personnel who need it, and
							monitoring for misuse. Measures are reviewed as risks and
							technology change.
						</p>
					),
				},
				{
					id: "subprocessors",
					heading: "5. Subprocessors",
					body: (
						<>
							<p>
								The Customer authorizes the subprocessors listed below to
								process workplace data. jooling will give the Customer advance
								notice of new or replacement subprocessors and an opportunity to
								object on reasonable data protection grounds.
							</p>
							<ul>
								{SUBPROCESSORS.map((subprocessor) => (
									<li key={subprocessor.name}>
										<strong>{subprocessor.name}</strong> —{" "}
										{subprocessor.purpose} ({subprocessor.location}).
									</li>
								))}
							</ul>
						</>
					),
				},
				{
					id: "transfers",
					heading: "6. International transfers",
					body: (
						<p>
							Where workplace data is transferred outside the EEA, the UK, or
							Switzerland, jooling relies on adequacy decisions or the European
							Commission's Standard Contractual Clauses (with the UK Addendum or
							Swiss annex where applicable) entered into with the relevant
							recipient, and ensures like protection for onward transfers.
							jooling conducts transfer impact assessments before onboarding a
							subprocessor in a new country.
						</p>
					),
				},
				{
					id: "audits",
					heading: "7. Audits",
					body: (
						<p>
							Upon the Customer's reasonable request, no more than once per year
							(and additionally after a personal data breach), jooling will make
							available documentation of its compliance with this DPA — such as
							security summaries and audit logs. Where that is insufficient for
							the Customer to verify compliance, the parties will agree in good
							faith on the scope of a further audit.
						</p>
					),
				},
				{
					id: "contact",
					heading: "8. Contact",
					body: (
						<p>
							Questions about this DPA can be sent to{" "}
							<a href={`mailto:${LEGAL_ENTITY.contactEmail}`}>
								{LEGAL_ENTITY.contactEmail}
							</a>
							. See also our <Link to="/privacy">Privacy Policy</Link> for how
							we handle data we control, such as account information.
						</p>
					),
				},
			]}
		/>
	);
}
